### ISSUE TITLE
Several improvements suggested

### ISSUE THREAD

**Issue by arteny** [jacobtread/obsidian-timekeep#10]
It will be great to see the following improvements for plugin: 
- possibility to sort work blocks by duration 
- possibility to collapse embedded blocks (Part 1, Part 2, Part 3..), because table became too large and bad readable 
- to highlight the currently running block in the table, because it is not understandable from main control which task is running when it is a next part and same part exist in other blocks, like:
```
Currently Running:
Name: Part 3
Started at: 24-07-18 19:57:04
```

**Comment by jacobtread** [comment]
What are your plans around sorting by duration? I don't see any use cases where that would be helpful.

Currently I have the default ordering which is insert ordering oldest -> newest then the reverse of that newest -> oldest which is helpful for seeing newest entries first. But I cannot see any case where ordering by longest/shortest would be useful or within scope. 

If you are wanting ordering based on duration for statistics reasoning you'd be better off using something like Obsidian Dataview and the API I've exposed in #8 to do your visualization that way with some scripting

**Comment by arteny** [comment]
> What are your plans around sorting by duration? I don't see any use cases where that would be helpful.
> 
> Currently I have the default ordering which is insert ordering oldest -> newest then the reverse of that newest -> oldest which is helpful for seeing newest entries first. But I cannot see any case where ordering by longest/shortest would be useful or within scope.
> 
> If you are wanting ordering based on duration for statistics reasoning you'd be better off using something like Obsidian Dataview and the API I've exposed in #8 to do your visualization that way with some scripting

I think it is the main user case for this plugin at all - the possibility to see which Block of time spending took most time.
Using from API may be useful, but need spend time to learning how to use it and additional space on page, when it would be much more easy if it could sort (at least by duration desc) directly in the main widget.

**Comment by jacobtread** [comment]
You would not be able to sort by a duration on the widget itself without also having to include the current sort mode inside the time keep data due to a limitation of how the app is rendered by Obsidian which I do not want to do as I believe it strays to far from data that should be included in the JSON. 

It would have to be a plugin setting like the reverse order option, applied to all. But I do not see the value in spending time to implement it at this stage for this plugin as it does not fit my use case, in which I track hours for billing clients and the time spent is not something that matters to me (Would be more relevant to use the API or a custom made tool to get those sort of insights). This may be implemented in the future but I do not see this as relevant for now.

I have implemented highlighting the active row and the collapsing of entries. 

Due to the limitations of how Obsidian renders the app local state will not persist as soon as any mutation happens on the timekeep (add/edit/remove/collapse/expand) the local state will be lost and the timekeep will do a full re-render thus storing local state to sort individual timekeeps is not possible. I have had to store a collapsed state for time keep entries in the timekeep data for that feature to work.

The changes mentioned will be in the next release of the plugin

**Comment by jacobtread** [comment]
The provided dataviewjs code will create a table for each entry (Only taking the first layer, any groups of entries will be the sum of the groups parts duration) and order the entries by longest to shortest:

You can find the Dataview js reference [Here](https://blacksmithgu.github.io/obsidian-dataview/api/intro/)
<details>

<summary>Dataview duration table code example</summary>

````
```dataviewjs
// Get the currently open file
const activeFile = this.app.workspace.getActiveFile();
if (!activeFile || !activeFile.name) return;

// Read the file
const text = await this.app.vault.read(activeFile);

// Get the timekeep plugin API
const timekeepPlugin = this.app.plugins.plugins.timekeep;

// Extract the timekeeps from the file text
const timekeeps = timekeepPlugin.extractTimekeepCodeblocks(text);

// Current time is required for unfinished entries
const currentTime = moment();

// Helper to format the duration number as human readable
function formatDuration(totalTime) {
	let ret = "";
	const duration = moment.duration(totalTime);
	const hours = Math.floor(duration.asHours());

	if (hours > 0) ret += hours + "h ";
	if (duration.minutes() > 0) ret += duration.minutes() + "m ";
	ret += duration.seconds() + "s";

	return ret.trim();
}

for (const timekeep of timekeeps) {
	let data = [];

	for (const entry of timekeep.entries) {
		let duration = 0;
		if (entry.subEntries !== null) {
			// Group entry total duration
			duration = timekeepPlugin.getTotalDuration(
				entry.subEntries,
				currentTime
			);
		} else {
			// Single entry duration
			duration = timekeepPlugin.getEntryDuration(entry, currentTime);
		}

		// Push the entry
		data.push([entry.name, duration]);
	}

	// Order the data by duration
	data.sort((a, b) => b[1] - a[1]);

	// Convert the durations to human readable
	const formattedData = data.map(([name, duration]) => [
		name,
		formatDuration(duration),
	]);

	// Put a table for the timekeep
	dv.table(["Name", "Duration"], formattedData);
}

```
````
</details>

This will produce:
![image](https://github.com/user-attachments/assets/dba08a78-2004-48a1-bcd0-18ed19361cf7)

**Comment by jacobtread** [comment]
You can find a copy of the dataview code at https://github.com/jacobtread/obsidian-timekeep/blob/main/test-vault/Dataview-Longest-Ordered-Example.md which also shows reading from a different file
